Check for the presence of Library and program
SalamLang/Salam pull request #113
Opened 2024-04-26 20:34 UTC by janus

Check for the presence of  efence Library and emcc program

2024-05-06 15:58 UTC, jbampton commented on b.sh
> +        echo "efence libraray is missing"
```suggestion
        echo "efence library is missing"
```

2024-05-07 20:23 UTC, jbampton requested changes
We are using tabs for indents in shell files.

Use `shfmt` to reformat etc 

https://github.com/mvdan/sh

See our default styles in the `.editorconfig` file

https://github.com/SalamLang/Salam/blob/8ffe13ed4a51a0af75856784dd2c74b906aef07e/.editorconfig#L18

2024-05-09 20:32 UTC, janus commented
> We are using tabs for indents in shell files.
> 
> Use `shfmt` to reformat etc
> 
> https://github.com/mvdan/sh
> 
> See our default styles in the `.editorconfig` file
> 
> https://github.com/SalamLang/Salam/blob/8ffe13ed4a51a0af75856784dd2c74b906aef07e/.editorconfig#L18

Alright

2024-05-26 07:51 UTC, merged

2024-05-26 07:52 UTC, erfangnu commented
merged.
thanks, let's push faster