Added some content to README_AR.md file
SalamLang/Salam pull request #121
Opened 2024-05-11 13:47 UTC by yOOs-dz

## Description

I added some Arabic content to the Arabic documentation page README_AR.md including : 

1. two phrases of presentation, 
2. a translation of titles,  keywords and operators. 
Hope this would help!

## Issues
Still need contributions!
Some RTL issues to fix here. It is my first try in translations :)

2024-05-11 14:32 UTC, jbampton commented on docs/README_AR.md
> +
```suggestion
```

2024-05-11 14:32 UTC, jbampton commented on docs/README_AR.md
> +
```suggestion
```

2024-05-11 14:32 UTC, jbampton commented on docs/README_AR.md
> +
```suggestion
```

2024-05-11 14:32 UTC, jbampton commented on docs/README_AR.md
> +
```suggestion
```

2024-05-11 14:36 UTC, jbampton commented on docs/README_AR.md
> +
```suggestion
```

2024-05-11 14:46 UTC, jbampton commented on docs/README_AR.md
> +`سلام` or `سَلَام`
```suggestion
`سلام` or `سَلَام`
```

2024-05-11 14:46 UTC, jbampton commented on docs/README_AR.md
> +مرحبا بكم في لغة البرمجة سلام!
```suggestion
مرحبا بكم في لغة البرمجة سلام!
```

2024-05-11 14:46 UTC, jbampton commented on docs/README_AR.md
> +سلام هو أول لغة برمجة فارسية/إيرانية
```suggestion
سلام هو أول لغة برمجة فارسية/إيرانية
```

2024-05-11 16:04 UTC, gabrahmad requested changes

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +ELSEIF      |   ثمإذا  |   واگرنه    |
ثم إذا

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +FALSE       |   غلط  |      غلط      |
خطأ ( better word in arabic)

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +RETURN      |   أرجع  |    برگشت     |
ارجع ( من غير همزة)

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +أكبر          |  >
أكبر من

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +أصغر          |  <
أصغر من

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +أكبر أو يساوي |  >=
أكبر من أو يساوي

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +أصغر أو يساوي |  <=
أصغر من أو يساوي

2024-05-11 16:04 UTC, gabrahmad commented on docs/README_AR.md
> +سلام هو أول لغة برمجة فارسية/إيرانية
سلام هي

2024-05-11 16:11 UTC, yOOs-dz commented on docs/README_AR.md
> +ELSEIF      |   ثمإذا  |   واگرنه    |
ربما يجدر وضعها في كلمة واحدة بدون فضاءات spaces. 
Any potential issues on putting spaces ? This is to check. Thanks for your comment.

2024-05-11 16:16 UTC, yOOs-dz commented on docs/README_AR.md
> +RETURN      |   أرجع  |    برگشت     |
أَرجِعْ. فعل رباعي من أَرْجَع.  همزة قطع. شكرا لرسالتك.

2024-05-11 16:20 UTC, yOOs-dz commented on docs/README_AR.md
> +FALSE       |   غلط  |      غلط      |
بالنسبة للعبارة المنطقيةTRUE or FALSE . لست أدري إن وجدت كلمات أفضل من صحيح-غلط(أو خطأ)؟ يرجى مراجعة الموضوع أكثر. إن وجدت مراجع معتمدة فسيكون الأمر أفضل ، لكن غلط كذلك كلمة عربية. شكرا للتعليق.

2024-05-11 16:23 UTC, gabrahmad commented on docs/README_AR.md
> +RETURN      |   أرجع  |    برگشت     |
صح 
عذرا هذا خطأ مني

2024-05-11 16:25 UTC, yOOs-dz commented on docs/README_AR.md
> +أصغر          |  <
شكرا. سأصححها.

2024-05-11 16:25 UTC, gabrahmad commented
لا أعلم اذا كنت وجدت حل لمشكلة التذكير و التأنيث في تغيير الأسماء و الصفات ام لا ؟
مثل Null منعدم أو منعدمة لو كانت عائدة علي مؤنث ؟
أم عندك طريقة اخرى للتعامل مع ذلك

2024-05-11 16:25 UTC, yOOs-dz commented on docs/README_AR.md
> +سلام هو أول لغة برمجة فارسية/إيرانية
شكرا.

2024-05-11 16:29 UTC, gabrahmad commented on docs/README_AR.md
> +FALSE       |   غلط  |      غلط      |
غلط بالفعل كلمة عربية 
لكن الأشهر كلغة فصحي خطأ 
كلا اللفظين صواب 
لكني رأيت كلمة خطأ سوف تكون أفضل

2024-05-11 16:36 UTC, gabrahmad commented on docs/README_AR.md
> +ELSEIF      |   ثمإذا  |   واگرنه    |
حتي الآن لم أجد حل لكني سوف أبحث 
أثناء البحث وجدت ان الافضل لفظا 
كلمة ( وإلا إذا) 
Else if = وإلا إذا 
Then if = ثم إذا

2024-05-11 18:49 UTC, yOOs-dz commented
> لا أعلم اذا كنت وجدت حل لمشكلة التذكير و التأنيث في تغيير الأسماء و الصفات ام لا ؟ مثل Null منعدم أو منعدمة لو كانت عائدة علي مؤنث ؟ أم عندك طريقة اخرى للتعامل مع ذلك

صحيح. يفترض التدقيق في أي سياق توضع. إذا كانت القيمة-value فهي مؤنثة. شكرا للمساهمة.

2024-05-11 19:10 UTC, yOOs-dz commented
Thanks to @jbampton and @gabrahmad to the very constructive reviews

2024-05-11 19:11 UTC, yOOs-dz commented
> لا أعلم اذا كنت وجدت حل لمشكلة التذكير و التأنيث في تغيير الأسماء و الصفات ام لا ؟ مثل Null منعدم أو منعدمة لو كانت عائدة علي مؤنث ؟ أم عندك طريقة اخرى للتعامل مع ذلك

شكرا. على الملاحظات القيمة. يفترض أنني صححت ما تذكرت منها.

2024-05-11 20:02 UTC, gabrahmad commented
> Thanks to @jbampton and @gabrahmad to the very constructive reviews

Thank you

2024-05-12 20:05 UTC, jbampton approved these changes
Thank you all !!

2024-05-12 20:07 UTC, merged